[[phrases]]
inul = "␀"

[[phrases]]
iinf = "∞"

[[phrases]]
inum = "№"


# Superscript Numbers
[[phrases]]
izero = "⁰"

[[phrases]]
ione = "¹"

[[phrases]]
itwo = "²"

[[phrases]]
ithree = "³"

[[phrases]]
ifour = "⁴"

[[phrases]]
ifive = "⁵"

[[phrases]]
isix = "⁶"

[[phrases]]
iseven = "⁷"

[[phrases]]
ieight = "⁸"

[[phrases]]
inine = "⁹"


# Subscript Numbers
[[phrases]]
izero = "₀"

[[phrases]]
ione = "₁"

[[phrases]]
itwo = "₂"

[[phrases]]
ithree = "₃"

[[phrases]]
ifour = "₄"

[[phrases]]
ifive = "₅"

[[phrases]]
isix = "₆"

[[phrases]]
iseven = "₇"

[[phrases]]
ieight = "₈"

[[phrases]]
inine = "₉"


# Circled Numbers
[[phrases]]
izero = "⓪"

[[phrases]]
ione = "①"

[[phrases]]
itwo = "②"

[[phrases]]
ithree = "③"

[[phrases]]
ifour = "④"

[[phrases]]
ifive = "⑤"

[[phrases]]
isix = "⑥"

[[phrases]]
iseven = "⑦"

[[phrases]]
ieight = "⑧"

[[phrases]]
inine = "⑨"


# Bold Numbers
[[phrases]]
izero = "𝟬"

[[phrases]]
ione = "𝟭"

[[phrases]]
itwo = "𝟮"

[[phrases]]
ithree = "𝟯"

[[phrases]]
ifour = "𝟰"

[[phrases]]
ifive = "𝟱"

[[phrases]]
isix = "𝟲"

[[phrases]]
iseven = "𝟳"

[[phrases]]
ieight = "𝟴"

[[phrases]]
inine = "𝟵"


# Operators
[[phrases]]
iplus = "±"

[[phrases]]
iplus = "₊"

[[phrases]]
iplus = "⁺"

[[phrases]]
iminus = "±"

[[phrases]]
iminus = "₋"

[[phrases]]
iminus = "⁻"

[[phrases]]
iequal = "₌"

[[phrases]]
iequal = "≥"

[[phrases]]
iequal = "≤"

[[phrases]]
iequal = "⁼"

[[phrases]]
iequal = "≠"

[[phrases]]
iequal = "≈"

[[phrases]]
iequal = "≡"

[[phrases]]
itimes = "×"

[[phrases]]
itimes = "˟"

[[phrases]]
idiv = "÷"  # Division Sign (U+00F7): '1 ÷ 2'

[[phrases]]
idiv = "∕"  # Standard Division Slash (U+2215): 'a∕b'

[[phrases]]
idiv = "ᐟ"  # Divide Modifier (U+141F): 'x¹ᐟ²'

[[phrases]]
ifrac = "⁄"  # Fraction Slash (U+2044): '1⁄2'
