[[phrases]]
iemoji = "️"  # Variation Selector-16 (U+FE0F) to ensure emoji presentation

[[phrases]]
ipro = "👍"

[[phrases]]
icon = "👎"

[[phrases]]
ilink = "🔗"

[[phrases]]
ilink = "⛓"  # ⛓️ (U+26D3)

[[phrases]]
ianchor = "⚓"

[[phrases]]
inote = "🗒"  # 🗒️ (U+1F5D2)

[[phrases]]
imemo = "📝"

[[phrases]]
ifolder = "📁"

[[phrases]]
ipage = "📄"

[[phrases]]
imouse = "🖱"  # 🖱️ (U+1F5B1)

[[phrases]]
istick = "🕹"  # 🕹️ (U+1F579)

[[phrases]]
igame = "🎮"

[[phrases]]
ichestnut = "🌰"

[[phrases]]
itag = "🏷"  # 🏷️ (U+1F3F7)

[[phrases]]
ibookmark = "🔖"

[[phrases]]
ibox = "🔲"

[[phrases]]
ibox = "🔘"

[[phrases]]
iok = "✔"  # Heavy Check Mark

[[phrases]]
iko = "❌"  # Cross Mark

[[phrases]]
iok = "✅"  # White Heavy Check Mark

[[phrases]]
iko = "❎"  # Negative Squared Cross Mark

[[phrases]]
iok = "🆗"  # Squared Ok

[[phrases]]
iko = "🈲"  # Prohibited

[[phrases]]
idot = "🔹"  # Small Blue Diamond

[[phrases]]
idot = "🔸"  # Small Orange Diamond

[[phrases]]
iempty = "🈳"

[[phrases]]
iplus = "➕"

[[phrases]]
iminus = "➖"

[[phrases]]
itimes = "✖"  # ✖️ (U+2716)

[[phrases]]
idiv = "➗"

[[phrases]]
ifish = "🐠"  # Small

[[phrases]]
idolphin = "🐬"  # Medium

[[phrases]]
iwhale = "🐳"  # Large

[[phrases]]
imale = "♂️"  # ♂ (U+2642)

[[phrases]]
ifemale = "♀️"  # ♀ (U+2640)
