[[phrases]]
ialpha = "Α"

[[phrases]]
ialpha = "α"

[[phrases]]
ialpha = "ᵅ"

[[phrases]]
ibeta = "Β"

[[phrases]]
ibeta = "β"

[[phrases]]
ibeta = "ᵝ"

[[phrases]]
ibeta = "ᵦ"

[[phrases]]
igamma = "Γ"

[[phrases]]
igamma = "γ"

[[phrases]]
idelta = "Δ"

[[phrases]]
idelta = "δ"

[[phrases]]
iepsilon = "Ε"

[[phrases]]
iepsilon = "ε"

[[phrases]]
izeta = "Ζ"

[[phrases]]
izeta = "ζ"

[[phrases]]
ieta = "Η"

[[phrases]]
ieta = "η"

[[phrases]]
itheta = "Θ"

[[phrases]]
itheta = "θ"

[[phrases]]
iiota = "Ι"

[[phrases]]
iiota = "ι"

[[phrases]]
ikappa = "Κ"

[[phrases]]
ikappa = "κ"

[[phrases]]
ilambda = "Λ"

[[phrases]]
ilambda = "λ"

[[phrases]]
imu = "Μ"

[[phrases]]
imu = "μ"

[[phrases]]
inu = "Ν"

[[phrases]]
inu = "ν"

[[phrases]]
ixi = "Ξ"

[[phrases]]
ixi = "ξ"

[[phrases]]
iomicron = "Ο"

[[phrases]]
iomicron = "ο"

[[phrases]]
ipi = "Π"

[[phrases]]
ipi = "π"

[[phrases]]
irho = "Ρ"

[[phrases]]
irho = "ρ"

[[phrases]]
isigma = "Σ"

[[phrases]]
isigma = "σ"

[[phrases]]
isigma = "ς"

[[phrases]]
itau = "Τ"

[[phrases]]
itau = "τ"

[[phrases]]
iupsilon = "Υ"

[[phrases]]
iupsilon = "υ"

[[phrases]]
iphi = "Φ"

[[phrases]]
iphi = "φ"

[[phrases]]
ichi = "Χ"

[[phrases]]
ichi = "χ"

[[phrases]]
ipsi = "Ψ"

[[phrases]]
ipsi = "ψ"

[[phrases]]
iomega = "Ω"

[[phrases]]
iomega = "ω"
