# small chars
[[phrases]]
iva = "ᵃ"

[[phrases]]
iva = "ₐ"

[[phrases]]
ivb = "ᵇ"

[[phrases]]
ivc = "ᶜ"

[[phrases]]
ivd = "ᵈ"

[[phrases]]
ive = "ₑ"

[[phrases]]
ive = "ᵉ"

[[phrases]]
ive = "ₔ"

[[phrases]]
ivf = "ᶠ"

[[phrases]]
ivg = "ᵍ"

[[phrases]]
ivh = "ʰ"

[[phrases]]
ivh = "ₕ"

[[phrases]]
ivi = "ᵢ"

[[phrases]]
ivi = "ⁱ"

[[phrases]]
ivi = "ᵎ"

[[phrases]]
ivj = "ʲ"

[[phrases]]
ivj = "ⱼ"

[[phrases]]
ivk = "ᵏ"

[[phrases]]
ivk = "ₖ"

[[phrases]]
ivl = "ˡ"

[[phrases]]
ivl = "ₗ"

[[phrases]]
ivm = "ᵐ"

[[phrases]]
ivm = "ₘ"

[[phrases]]
ivn = "ⁿ"

[[phrases]]
ivn = "ₙ"

[[phrases]]
ivo = "ᵒ"

[[phrases]]
ivo = "ₒ"

[[phrases]]
ivp = "ᵖ"

[[phrases]]
ivp = "ₚ"

[[phrases]]
ivr = "ʳ"

[[phrases]]
ivr = "ᵣ"

[[phrases]]
ivs = "ˢ"

[[phrases]]
ivs = "ₛ"

[[phrases]]
ivt = "ᵗ"

[[phrases]]
ivt = "ₜ"

[[phrases]]
ivu = "ᵘ"

[[phrases]]
ivu = "ᵤ"

[[phrases]]
ivv = "ᵛ"

[[phrases]]
ivv = "ᵥ"

[[phrases]]
ivw = "ʷ"

[[phrases]]
ivx = "ˣ"

[[phrases]]
ivx = "ₓ"

[[phrases]]
ivy = "ʸ"

[[phrases]]
ivz = "ᶻ"

# Tones
[[phrases]]
iva = "ā"

[[phrases]]
iva = "á"

[[phrases]]
iva = "ǎ"

[[phrases]]
iva = "à"

[[phrases]]
ive = "ē"

[[phrases]]
ive = "é"

[[phrases]]
ive = "ě"

[[phrases]]
ive = "è"

[[phrases]]
ivi = "ī"

[[phrases]]
ivi = "í"

[[phrases]]
ivi = "ǐ"

[[phrases]]
ivi = "ì"

[[phrases]]
ivo = "ō"

[[phrases]]
ivo = "ó"

[[phrases]]
ivo = "ǒ"

[[phrases]]
ivo = "ò"

[[phrases]]
ivu = "ū"

[[phrases]]
ivu = "ú"

[[phrases]]
ivu = "ǔ"

[[phrases]]
ivu = "ù"

# Mathematical Sans-Serif Bold Italic
[[phrases]]
iva = "𝘼"

[[phrases]]
ivb = "𝘽"

[[phrases]]
ivc = "𝘾"

[[phrases]]
ivd = "𝘿"

[[phrases]]
ive = "𝙀"

[[phrases]]
ivf = "𝙁"

[[phrases]]
ivg = "𝙂"

[[phrases]]
ivh = "𝙃"

[[phrases]]
ivi = "𝙄"

[[phrases]]
ivj = "𝙅"

[[phrases]]
ivk = "𝙆"

[[phrases]]
ivl = "𝙇"

[[phrases]]
ivm = "𝙈"

[[phrases]]
ivn = "𝙉"

[[phrases]]
ivo = "𝙊"

[[phrases]]
ivp = "𝙋"

[[phrases]]
ivq = "𝙌"

[[phrases]]
ivr = "𝙍"

[[phrases]]
ivs = "𝙎"

[[phrases]]
ivt = "𝙏"

[[phrases]]
ivu = "𝙐"

[[phrases]]
ivv = "𝙑"

[[phrases]]
ivw = "𝙒"

[[phrases]]
ivx = "𝙓"

[[phrases]]
ivy = "𝙔"

[[phrases]]
ivz = "𝙕"

[[phrases]]
iva = "𝙖"

[[phrases]]
ivb = "𝙗"

[[phrases]]
ivc = "𝙘"

[[phrases]]
ivd = "𝙙"

[[phrases]]
ive = "𝙚"

[[phrases]]
ivf = "𝙛"

[[phrases]]
ivg = "𝙜"

[[phrases]]
ivh = "𝙝"

[[phrases]]
ivi = "𝙞"

[[phrases]]
ivj = "𝙟"

[[phrases]]
ivk = "𝙠"

[[phrases]]
ivl = "𝙡"

[[phrases]]
ivm = "𝙢"

[[phrases]]
ivn = "𝙣"

[[phrases]]
ivo = "𝙤"

[[phrases]]
ivp = "𝙥"

[[phrases]]
ivq = "𝙦"

[[phrases]]
ivr = "𝙧"

[[phrases]]
ivs = "𝙨"

[[phrases]]
ivt = "𝙩"

[[phrases]]
ivu = "𝙪"

[[phrases]]
ivv = "𝙫"

[[phrases]]
ivw = "𝙬"

[[phrases]]
ivx = "𝙭"

[[phrases]]
ivy = "𝙮"

[[phrases]]
ivz = "𝙯"

# Mathematical Script
[[phrases]]
iva = "𝒜"

[[phrases]]
ivb = "ℬ"

[[phrases]]
ivc = "𝒞"

[[phrases]]
ivd = "𝒟"

[[phrases]]
ive = "ℰ"

[[phrases]]
ivf = "ℱ"

[[phrases]]
ivg = "𝒢"

[[phrases]]
ivh = "ℋ"

[[phrases]]
ivi = "ℐ"

[[phrases]]
ivj = "𝒥"

[[phrases]]
ivk = "𝒦"

[[phrases]]
ivl = "ℒ"

[[phrases]]
ivm = "ℳ"

[[phrases]]
ivn = "𝒩"

[[phrases]]
ivo = "𝒪"

[[phrases]]
ivp = "𝒫"

[[phrases]]
ivq = "𝒬"

[[phrases]]
ivr = "ℛ"

[[phrases]]
ivs = "𝒮"

[[phrases]]
ivt = "𝒯"

[[phrases]]
ivu = "𝒰"

[[phrases]]
ivv = "𝒱"

[[phrases]]
ivw = "𝒲"

[[phrases]]
ivx = "𝒳"

[[phrases]]
ivy = "𝒴"

[[phrases]]
ivz = "𝒵"

[[phrases]]
iva = "𝒶"

[[phrases]]
ivb = "𝒷"

[[phrases]]
ivc = "𝒸"

[[phrases]]
ivd = "𝒹"

[[phrases]]
ive = "ℯ"

[[phrases]]
ivf = "𝒻"

[[phrases]]
ivg = "ℊ"

[[phrases]]
ivh = "𝒽"

[[phrases]]
ivi = "𝒾"

[[phrases]]
ivj = "𝒿"

[[phrases]]
ivk = "𝓀"

[[phrases]]
ivl = "𝓁"

[[phrases]]
ivm = "𝓂"

[[phrases]]
ivn = "𝓃"

[[phrases]]
ivo = "ℴ"

[[phrases]]
ivp = "𝓅"

[[phrases]]
ivq = "𝓆"

[[phrases]]
ivr = "𝓇"

[[phrases]]
ivs = "𝓈"

[[phrases]]
ivt = "𝓉"

[[phrases]]
ivu = "𝓊"

[[phrases]]
ivv = "𝓋"

[[phrases]]
ivw = "𝓌"

[[phrases]]
ivx = "𝓍"

[[phrases]]
ivy = "𝓎"

[[phrases]]
ivz = "𝓏"

[[phrases]]
ibp = "Best Practice"

[[phrases]]
ikb = "Knowledge Base"
