[[phrases]]
iemoji = "️"  # Variation Selector-16 (U+FE0F): ensure emoji presentation

[[phrases]]
ipro = "👍"

[[phrases]]
icon = "👎"

[[phrases]]
ilink = "🔗"  # Link Symbol (U+1F517)

[[phrases]]
ilink = "⛓"  # Chains (U+26D3): ⛓️ +(U+FE0F)

[[phrases]]
ianchor = "⚓"  # Anchor (U+2693)

[[phrases]]
inote = "🗒"  # Spiral Note Pad (U+1F5D2): 🗒️ +(U+FE0F)

[[phrases]]
imemo = "📝"

[[phrases]]
ifolder = "📁"

[[phrases]]
ipage = "📄"

[[phrases]]
imouse = "🖱"  # Three Button Mouse (U+1F5B1): 🖱️ +(U+FE0F)

[[phrases]]
istick = "🕹"  # Joystick (U+1F579): 🕹️ +(U+FE0F)

[[phrases]]
igame = "🎮"  # Video Game (U+1F3AE)

[[phrases]]
ichestnut = "🌰"  # Chestnut (U+1F330)

[[phrases]]
itag = "🏷"  # Label (U+1F3F7): 🏷️ +(U+FE0F)

[[phrases]]
ibookmark = "🔖"

[[phrases]]
ibox = "🔲"

[[phrases]]
ibox = "🔘"

[[phrases]]
icoin = "🪙"  # Coin (U+1FA99)

[[phrases]]
iok = "✔"  # Heavy Check Mark

[[phrases]]
iko = "❌"  # Cross Mark

[[phrases]]
iok = "✅"  # White Heavy Check Mark

[[phrases]]
iko = "❎"  # Negative Squared Cross Mark

[[phrases]]
iok = "🆗"  # Squared Ok

[[phrases]]
iko = "🈲"  # Prohibited

[[phrases]]
idot = "🔹"  # Small Blue Diamond (U+1F539)

[[phrases]]
idot = "🔸"  # Small Orange Diamond (U+1F538)

[[phrases]]
idot = "💠"  # Diamond Shape with a Dot Inside (U+1F48E)

[[phrases]]
iempty = "🈳"

[[phrases]]
iplus = "➕"  # Heavy Plus Sign (U+2795)

[[phrases]]
iminus = "➖"  # Heavy Minus Sign (U+2796)

[[phrases]]
itimes = "✖️"  # Heavy Multiplication X (U+2716): ✖ + (U+FE0F)

[[phrases]]
idiv = "➗"  # Heavy Division Sign (U+2797)

[[phrases]]
ifish = "🐠"  # Tropical Fish (U+1F420): Small

[[phrases]]
idolphin = "🐬"  # Dolphin (U+1F42C): Medium

[[phrases]]
iwhale = "🐳"  # Spouting Whale (U+1F433): Large

[[phrases]]
imale = "🚹"  # Mens Symbol (U+1F6B9)

[[phrases]]
ifemale = "🚺"  # Womens Symbol (U+1F6BA)
