[[phrases]]
iapple = ""

[[phrases]]
icut = "✄"

[[phrases]]
ibox = "☐"

[[phrases]]
iok = "✓"  # Check Mark

[[phrases]]
iko = "✗"  # Ballot X

[[phrases]]
iok = "☑"  # Ballot Box with Check

[[phrases]]
iko = "☒"  # Ballot Box with X

[[phrases]]
iempty = "∅"

[[phrases]]
ibar = "｜"

[[phrases]]
idot = "・"

[[phrases]]
iquote = "｀"  # Fullwidth

[[phrases]]
iquote = "′"  # Prime: feet, minutes

[[phrases]]
iquote = "″"  # Double Prime: inches, seconds

[[phrases]]
isquare = "▢"

[[phrases]]
isquare = "⬚"

[[phrases]]
icircle = "◯"

[[phrases]]
itriangle = "⟁"

[[phrases]]
icross = "⛌"

[[phrases]]
imale = "♂"

[[phrases]]
ifemale = "♀"

[[phrases]]
icopr = "©"

[[phrases]]
ireg = "®"

[[phrases]]
iphono = "Ⓟ"

[[phrases]]
itel = "℡"

[[phrases]]
itm = "™"

[[phrases]]
ism = "℠"

[[phrases]]
idagger = "†"

[[phrases]]
ideg = "°"

[[phrases]]
ilove = "❤"

[[phrases]]
ipara = "¶"  # Pilcrow

[[phrases]]
isect = "§"  # Section Sign

[[phrases]]
iparty = "☭"

[[phrases]]
istar = "★"

[[phrases]]
istar = "☆"

[[phrases]]
itaichi = "☯"

[[phrases]]
ii = "「"  # Single Quote Brackets

[[phrases]]
io = "」"

[[phrases]]
ii = "『"  # Double Quote Brackets

[[phrases]]
io = "』"

[[phrases]]
ii = "〖"  # White Lenticular Brackets

[[phrases]]
io = "〗"

[[phrases]]
ii = "〔"  # Tortoise Shell Brackets

[[phrases]]
io = "〕"

[[phrases]]
ii = "⁽"  # Superscript Parentheses

[[phrases]]
io = "⁾"

[[phrases]]
ii = "₍"  # Subscript Parentheses

[[phrases]]
io = "₎"

[[phrases]]
isharp = "♯"  # Sharp

[[phrases]]
iflat = "♭"  # Flat

[[phrases]]
imusic = "♪"

[[phrases]]
imusic = "♬"

[[phrases]]
imusic = "𝄞"  # Gclef

[[phrases]]
irmb = "¥"

[[phrases]]
idc = "⎓"

[[phrases]]
islash = "／"  # Fullwidth of "/" (U+FF0F): '米／秒'
