[[phrases]]
va = "ア"

[[phrases]]
vi = "イ"

[[phrases]]
vu = "ウ"

[[phrases]]
ve = "エ"

[[phrases]]
vo = "オ"

[[phrases]]
vka = "カ"

[[phrases]]
vki = "キ"

[[phrases]]
vku = "ク"

[[phrases]]
vke = "ケ"

[[phrases]]
vko = "コ"

[[phrases]]
vkya = "キャ"

[[phrases]]
vkyu = "キュ"

[[phrases]]
vkye = "キェ"

[[phrases]]
vkyo = "キョ"

[[phrases]]
vga = "ガ"

[[phrases]]
vgi = "ギ"

[[phrases]]
vgu = "グ"

[[phrases]]
vge = "ゲ"

[[phrases]]
vgo = "ゴ"

[[phrases]]
vgya = "ギャ"

[[phrases]]
vgyu = "ギュ"

[[phrases]]
vgye = "ギェ"

[[phrases]]
vgyo = "ギョ"

[[phrases]]
vsa = "サ"

[[phrases]]
vshi = "シ"

[[phrases]]
vsu = "ス"

[[phrases]]
vse = "セ"

[[phrases]]
vso = "ソ"

[[phrases]]
vsha = "シャ"

[[phrases]]
vshu = "シュ"

[[phrases]]
vshe = "シェ"

[[phrases]]
vsho = "ショ"

[[phrases]]
vza = "ザ"

[[phrases]]
vji = "ジ"

[[phrases]]
vzu = "ズ"

[[phrases]]
vze = "ゼ"

[[phrases]]
vzo = "ゾ"

[[phrases]]
vja = "ジャ"

[[phrases]]
vzi = "ズィ"

[[phrases]]
vju = "ジュ"

[[phrases]]
vje = "ジェ"

[[phrases]]
vjo = "ジョ"

[[phrases]]
vta = "タ"

[[phrases]]
vchi = "チ"

[[phrases]]
vtsu = "ツ"

[[phrases]]
vte = "テ"

[[phrases]]
vto = "ト"

[[phrases]]
vtsa = "ツァ"

[[phrases]]
vtsi = "ツィ"

[[phrases]]
vtse = "ツェ"

[[phrases]]
vtso = "ツォ"

[[phrases]]
vcha = "チャ"

[[phrases]]
vchu = "チュ"

[[phrases]]
vche = "チェ"

[[phrases]]
vcho = "チョ"

[[phrases]]
vda = "ダ"

[[phrases]]
vdji = "ヂ"

[[phrases]]
vdu = "ヅ"

[[phrases]]
vde = "デ"

[[phrases]]
vdo = "ド"

[[phrases]]
vdja = "ヂャ"

[[phrases]]
vdi = "ディ"

[[phrases]]
vdju = "ヂュ"

[[phrases]]
vdje = "ヂェ"

[[phrases]]
vdjo = "ヂョ"

[[phrases]]
vna = "ナ"

[[phrases]]
vni = "ニ"

[[phrases]]
vnu = "ヌ"

[[phrases]]
vne = "ネ"

[[phrases]]
vno = "ノ"

[[phrases]]
vnya = "ニャ"

[[phrases]]
vnyu = "ニュ"

[[phrases]]
vnye = "ニェ"

[[phrases]]
vnyo = "ニョ"

[[phrases]]
vha = "ハ"

[[phrases]]
vhi = "ヒ"

[[phrases]]
vfu = "フ"

[[phrases]]
vhe = "ヘ"

[[phrases]]
vho = "ホ"

[[phrases]]
vhya = "ヒャ"

[[phrases]]
vhyu = "ヒょ"

[[phrases]]
vhye = "ヒェ"

[[phrases]]
vhyo = "ヒョ"

[[phrases]]
vba = "バ"

[[phrases]]
vbi = "ビ"

[[phrases]]
vbu = "ブ"

[[phrases]]
vbe = "ベ"

[[phrases]]
vbo = "ボ"

[[phrases]]
vbya = "ビャ"

[[phrases]]
vbyu = "ビュ"

[[phrases]]
vbye = "ビェ"

[[phrases]]
vbyo = "ビョ"

[[phrases]]
vpa = "パ"

[[phrases]]
vpi = "ピ"

[[phrases]]
vpu = "プ"

[[phrases]]
vpe = "ペ"

[[phrases]]
vpo = "ポ"

[[phrases]]
vpya = "ピャ"

[[phrases]]
vpyu = "ピュ"

[[phrases]]
vpye = "ピェ"

[[phrases]]
vpyo = "ピョ"

[[phrases]]
vma = "マ"

[[phrases]]
vmi = "ミ"

[[phrases]]
vmu = "ム"

[[phrases]]
vme = "メ"

[[phrases]]
vmo = "モ"

[[phrases]]
vmya = "ミャ"

[[phrases]]
vmyu = "ミュ"

[[phrases]]
vmye = "ミェ"

[[phrases]]
vmyo = "ミョ"

[[phrases]]
vya = "ヤ"

[[phrases]]
vyo = "ヨ"

[[phrases]]
vyu = "ユ"

[[phrases]]
vra = "ラ"

[[phrases]]
vri = "リ"

[[phrases]]
vru = "ル"

[[phrases]]
vre = "レ"

[[phrases]]
vro = "ロ"

[[phrases]]
vrya = "リャ"

[[phrases]]
vryu = "リュ"

[[phrases]]
vrye = "リェ"

[[phrases]]
vryo = "リョ"

[[phrases]]
vwa = "ワ"

[[phrases]]
vwi = "ヰ"

[[phrases]]
vwe = "ヱ"

[[phrases]]
vwo = "ヲ"

[[phrases]]
vva = "ヴァ"

[[phrases]]
vvi = "ヴィ"

[[phrases]]
vvu = "ヴ"

[[phrases]]
vve = "ヴェ"

[[phrases]]
vvo = "ヴォ"

[[phrases]]
vnn = "ン"

[[phrases]]
vn = "ン"

[[phrases]]
vtt = "ッ"

[[phrases]]
vyy = "ー"

[[phrases]]
vxa = "ァ"

[[phrases]]
vxi = "ィ"

[[phrases]]
vxu = "ゥ"

[[phrases]]
vxe = "ェ"

[[phrases]]
vxo = "ォ"

[[phrases]]
vxka = "ヵ"

[[phrases]]
vxke = "ヶ"

[[phrases]]
vxwa = "ヮ"

[[phrases]]
vxya = "ャ"

[[phrases]]
vxyu = "ュ"

[[phrases]]
vxyo = "ョ"
